# Generated by Django 2.0.4 on 2018-04-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='call',
            field=models.ForeignKey(on_delete=True, related_name='records', to='call.Call'),
        ),
    ]
